// Code generated by "stringer -type=Label -output=enum_strings.go"; DO NOT EDIT.

package metrics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParseJSON-1]
	_ = x[LexJSON-2]
	_ = x[LexJSONClean-3]
	_ = x[ReferenceHaversine-4]
	_ = x[RecursiveHaversine-5]
	_ = x[PartnerHaversine-6]
	_ = x[ReadFile-7]
}

const _Label_name = "ParseJSONLexJSONLexJSONCleanReferenceHaversineRecursiveHaversinePartnerHaversineReadFile"

var _Label_index = [...]uint8{0, 9, 16, 28, 46, 64, 80, 88}

func (i Label) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Label_index)-1 {
		return "Label(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Label_name[_Label_index[idx]:_Label_index[idx+1]]
}
