// Code generated by "stringer -type=Label -output=enum_strings.go"; DO NOT EDIT.

package metrics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParseJSON-1]
	_ = x[QuickParse-2]
	_ = x[ParallelParse-3]
	_ = x[LexJSON-4]
	_ = x[LexJSONClean-5]
	_ = x[ReferenceHaversine-6]
	_ = x[RecursiveHaversine-7]
	_ = x[PartnerHaversine-8]
	_ = x[ReadFile-9]
}

const _Label_name = "ParseJSONQuickParseParallelParseLexJSONLexJSONCleanReferenceHaversineRecursiveHaversinePartnerHaversineReadFile"

var _Label_index = [...]uint8{0, 9, 19, 32, 39, 51, 69, 87, 103, 111}

func (i Label) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Label_index)-1 {
		return "Label(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Label_name[_Label_index[idx]:_Label_index[idx+1]]
}
